[workspace]
members = [
  "crates/front",
  "crates/back",
  "crates/other",
  "crates/users",
  "crates/communities",
  "crates/posts",
  "crates/files",
]

[[bin]]
name = "users"
path = "crates/users"
test = false

[[bin]]
name = "posts"
path = "crates/posts"
test = false
