[tasks.users]
command = "cargo"
args = ["run", "--bin users"]

[tasks.back]
command = "cargo"
args = ["run", "--bin back"]

[tasks.front]
command = "cargo"
args = ["run", "--bin front"]

[tasks.run-members]
command = "cargo"
args = ["run", "--bin files"]
dependencies = [
    #"users",
    #"back",
    "front"
]
