[tasks.users]
command = "cargo"
args = ["run", "--bin", "users"]

[tasks.back]
command = "cargo"
args = ["run", "--bin", "back"]

[tasks.front]
command = "cargo"
args = ["run", "--bin", "front"]

[tasks.run-members]
dependencies = [
    "users",
    "back",
    "front"
]
