[build]
target = "index.html"
# Build in release mode.
release = false

[serve]
# The address to serve on.
address = "194.58.90.123"
# The port to serve on.
port = 8100

[[proxy]]
# В этом примере прокси-сервера есть серверная часть и поле перезаписи. Запросы, полученные на `перезапись`, будут
# # проксируется на серверную часть после перезаписи префикса `rewrite` на префикс URL-адреса `backend'.
# Например, `/api/v1/resource/x/y/z` -> `/resource/x/y/z`
rewrite = "/tutorial/"
backend = "https://yew.rs/tutorial/"

#[[proxy]]
# В этом примере прокси-сервера WebSocket есть серверная часть и поле ws. В этом примере будет прослушиваться
# Подключения к WebSocket в `/api/ws` и прокси-сервер для `ws://localhost:9000/api/ws`.
#backend = "ws://localhost:9000/api/ws"
#ws = true
